env:
  node: true
  es2021: true
extends:
  - standard-with-typescript
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
rules:
  "@typescript-eslint/no-namespace": off
