name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs['packages-aldrin--release_created'] }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs['packages-aldrin--release_created'] }}
      - run: npm ci
        if: ${{ steps.release.outputs['packages-aldrin--release_created'] }}
      - run: npm run build
        if: ${{ steps.release.outputs['packages-aldrin--release_created'] }}
      - run: cd ./packages/aldrin && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs['packages-aldrin--release_created'] }}
